services:
  doctrine_phpcr.meta_cache_provider:
    class: Doctrine\Common\Cache\Psr6\DoctrineProvider
    factory: ['Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap']

  doctrine_phpcr.nodes_cache_provider:
    class: Doctrine\Common\Cache\Psr6\DoctrineProvider
    factory: ['Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap']

parameters:
    env(PHPCR_WORKSPACE): 'default'

sulu_document_manager:
    versioning:
        enabled: false # See https://docs.sulu.io/en/2.0/bundles/page/versioning.html if you want to enable versioning
    sessions:
        # See https://docs.sulu.io/en/2.0/cookbook/jackrabbit.html if you want to use Jackrabbit
        default:
            backend:
                type: doctrinedbal
            workspace: "%env(PHPCR_WORKSPACE)%"
        live:
            backend:
                type: doctrinedbal
            workspace: "%env(PHPCR_WORKSPACE)%_live"
