sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
      albums:
        routes:
          list: 'app.get_album_list'
          detail: 'app.get_album'
      clientrequestrefactorings:
        routes:
          list: 'app.get_clientrequestrefactoring_list'
          detail: 'app.get_clientrequestrefactoring'
    field_type_options:
      selection:
        album_selection:
          default_type: 'list_overlay'
          resource_key: 'albums'
          view:
            name: 'app.album.edit_form'
            result_to_view:
              id: 'id'
          types:
            list_overlay:
              adapter: 'table'
              list_key: 'albums'
              display_properties:
                - 'title'
              icon: 'su-storage'
              label: 'app.album_selection_label'
              overlay_title: 'app.select_albums'
      single_selection:
        single_album_selection:
          default_type: 'list_overlay'
          resource_key: 'albums'
          view:
            name: 'app.album.edit_form'
            result_to_view:
              id: 'id'
          types:
            list_overlay:
              adapter: 'table'
              list_key: 'albums'
              display_properties:
                - 'title'
              icon: 'su-storage'
              empty_text: 'app.no_album_selected'
              overlay_title: 'app.select_album'
