#!/bin/bash

[ -n "$APP_ENV" ] && echo "APP_ENV=$APP_ENV" > .env
[ -n "$APP_SECRET" ] && echo "APP_SECRET=$APP_SECRET" >> .env
[ -n "$DATABASE_URL" ] && echo "DATABASE_URL=$DATABASE_URL" >> .env
[ -n "$GOOGLE_API_KEY" ] && echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> .env
[ -n "$ELASTICSEARCH_HOST" ] && echo "ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST" >> .env
[ -n "$ELASTICSEARCH_INDEX" ] && echo "ELASTICSEARCH_INDEX=$ELASTICSEARCH_INDEX" >> .env
[ -n "$TWITTER_API_KEY" ] && echo "TWITTER_API_KEY=$TWITTER_API_KEY" >> .env
[ -n "$TWITTER_API_SECRET" ] && echo "TWITTER_API_SECRET=$TWITTER_API_SECRET" >> .env
[ -n "$TWITTER_ACCESS_TOKEN" ] && echo "TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN" >> .env
[ -n "$TWITTER_ACCESS_SECRET" ] && echo "TWITTER_ACCESS_SECRET=$TWITTER_ACCESS_SECRET" >> .env

exec "$@"
