# config/services_ai.yaml
services:
    # Gemini AI Provider
    App\AI\GeminiProvider:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%'
            $model: '%env(default:gemini-1.5-flash:GEMINI_MODEL)%'
            $baseUrl: '%env(default:https://generativelanguage.googleapis.com/v1beta:GEMINI_BASE_URL)%'
    
    # AI Platform - unified interface
    App\AI\Platform\AIPlatform:
        calls:
            - method: addProvider
              arguments:
                - 'gemini'
                - '@App\AI\GeminiProvider'
            - method: setDefaultProvider
              arguments:
                - 'gemini'
        
    # AI Content Service
    App\AI\AIContentService:
        arguments:
            $enabled: '%env(bool:default:true:AI_ENABLED)%'
        
    # Aliases for easy access
    ai.content: '@App\AI\AIContentService'
    ai.platform: '@App\AI\Platform\AIPlatform'
    ai.gemini: '@App\AI\GeminiProvider'